

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!> \file runderiv.f90
!
!> DESCRIPTION: driver to test generated derivative codes of the BEPS model
!               generated by The Inversion Lab with AD tool Tapenade.
!
!               Depending on the preprocessor flag passed
!               (DERIV_FW,DERIV_BW,DERIV_FWV) this driver is capable to create
!               the Jacobian of the function 'evalf' based on
!               - scalar forward derivative
!               - scalar backward derivative
!               - vector forward deriative
!               code respectively.
!               
!
!> \date  March  2020
!> \last  April  2021
!                               
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!+++++++++++++++++++++++++++++++++++++++++++++++++
!
!                    main
!
!
program main
  use mo_bepsfunc_ctl, only:enable_netcdf_out
  implicit none

  !defaults
  ! handling cmdline
  integer::narg,cptArg !#of arg & counter of arg
  integer :: nconsumed
  character(len=32) :: argname !Arg name
  character(len=32) :: argval
  !--
  character(len=32) :: mode = 'jacfwv'

  !Check if any arguments are found
  narg=command_argument_count()
  !Loop over the arguments
  if(narg>0)then
     !loop across options
     nconsumed=0
     arg: do cptArg=1,narg
        if( nconsumed.gt.0 ) then
           nconsumed = nconsumed - 1
           cycle arg
        endif
        call get_command_argument(cptArg,argname)
        select case(adjustl(argname))
        case("--help","-h")
           write(*,'(/)')
           write(*,*)" This is program 'main'"
           call dump_options()
           stop 0
           exit arg
        case('--mode')
           call get_command_argument(cptArg+1, mode)
           nconsumed = 1
        case default
           write(*,*)"Option ",adjustl(argname),"unknown"
           write(*,'(a)') "Available options:"
           call dump_options()
           stop 0
        end select
     end do arg
  end if

  !-- disable NetCDF output generation when computing derivatives
  write(*, '(1x,a)') 'INFO::NetCDF output is disabled for derivative generation.'
  enable_netcdf_out = .false.
    
  select case( mode )
  case default
     write(*,'(a)') ' FATAL::runbwcheck:unexpected mode ---'//trim(mode)//'---'
     stop 
  end select

contains

  subroutine dump_options()
    implicit none
    character(len=15) :: option
    write(*,'(a)') '=============================='
    write(*,*) " Options:"
    write(*,'(/)')
    option = "--mode"
    write(*,'(2x, a15,2x,a,a,a)') option,&
         &"which operation to apply "&
         &//"(default:",mode,")"
    write(*,'(2/)')
  end subroutine dump_options









end program main
